site_name: Aliakbar Nafar (Darius)
site_description: Research in NLP, LLMs, and neuro-symbolic reasoning
site_url: https://dariusnafar.github.io
repo_url: https://github.com/DariusNafar/DariusNafar.github.io
theme:
  name: null
  custom_dir: 'cinder'

nav:
  - Home: index.md
  - Research: research.md
  - Publications: publications.md
  - Work Experience: work.md
  - Talks & Presentations: talks.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - def_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DariusNafar
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anafar/
      name: LinkedIn
    - icon: simple/googlescholar
      link: https://scholar.google.com/citations?user=RnsQD44AAAAJ&hl=en
      name: Google Scholar
  meta:
    - name: description
      content: Research in NLP, LLMs, and neuro-symbolic reasoning by Darius (CS PhD @ MSU)
    - property: og:title
      content: Darius — CS PhD @ MSU
    - property: og:description
      content: Research in NLP, LLMs, and neuro-symbolic reasoning
    - property: og:type
      content: website
    - property: og:url
      content: https://dariusnafar.github.io
    - property: og:image
      content: /assets/social-card.svg
    - name: twitter:card
      content: summary_large_image
    - name: twitter:title
      content: Darius — CS PhD @ MSU
    - name: twitter:description
      content: Research in NLP, LLMs, and neuro-symbolic reasoning
    - name: twitter:image
      content: /assets/social-card.svg

extra_css:
  - assets/overrides.css

plugins:
  - search
